---
driver: docker
driver_config:
  use_sudo: false
  forward: 4440:4440

platforms:
  - name: centos-6.6
    driver_config:
      dockerfile: Dockerfile

provisioner:
  name: salt_solo
  formula: rundeck
  state_top:
    base:
      '*':
        - rundeck
  pillars:
    top.sls:
      base:
        '*':
          - rundeck
    rundeck.sls:

suites:
  - name: default
  - name: config
    provisioner:
      pillars:
        rundeck.sls:
          rundeck:
            config:
              host: rundeck.local
              port: 80
              projects:
                storage: db
                dir: /home/rundeck/projects
                resources_file: resources.yml
            users:
              admin:
                password: admin
                groups:
                  - user
                  - admin
              user:
                password: passwd
                groups:
                  - user
