---
driver: docker
driver_config:
  use_sudo: false
  forward: 4440:4440

platforms:
  - name: centos-6.6
    driver_config:
      dockerfile: Dockerfile

provisioner:
  name: salt_solo
  formula: rundeck
  state_top:
    base:
      '*':
        - rundeck
  pillars:
    top.sls:
      base:
        '*':
          - rundeck
    rundeck.sls:

suites:
  - name: default
  - name: config
    provisioner:
      pillars:
        rundeck.sls:
          rundeck:
            config:
              host: rundeck.local
              port: 80
              projects:
                storage: db
                dir: /home/rundeck/projects
                resources_file: resources.yml
            users:
              admin:
                password: admin
                groups:
                  - user
                  - admin
              user:
                password: passwd
                groups:
                  - user
  - name: projects-default
    provisioner:
      state_top:
        base:
          '*':
            - rundeck
            - rundeck.projects
      pillars:
        rundeck.sls:
          rundeck:
            projects:
              my-project:
  - name: projects-resources
    provisioner:
      state_top:
        base:
          '*':
            - rundeck
            - rundeck.projects
      pillars:
        rundeck.sls:
          rundeck:
            projects:
              directory:
                resources:
                  - source: directory
                    directory: /var/rundeck/projects/${project.name}/etc/resources
              script:
                resources:
                  - source: script
                    script: /usr/bin/rd-jobs
                  - source: script
                    format: resourceyaml
                    script: /usr/bin/rd-queue
                    interpreter: /bin/sh
                    args: nodes
                    quote_interpreter_args: True
              url:
                resources:
                  - source: url
                    url: http://localhost/nodes.xml
                  - source: url
                    url: http://localhost/nodes2.xml
                    timeout: 1800
                    cache: False
