---
driver: docker
driver_config:
  use_sudo: false
  forward: 4440:4440

platforms:
  - name: centos-6.6
    driver_config:
      dockerfile: Dockerfile

provisioner:
  name: salt_solo
  formula: rundeck
  state_top:
    base:
      '*':
        - rundeck
  pillars:
    top.sls:
      base:
        '*':
          - rundeck
    rundeck.sls:

suites:
  - name: default
  - name: config
    provisioner:
      pillars:
        rundeck.sls:
          rundeck:
            config:
              host: rundeck.local
              port: 80
              projects:
                storage: db
                dir: /home/rundeck/projects
                resources_file: resources.yml
            users:
              admin:
                password: admin
                groups:
                  - user
                  - admin
              user:
                password: passwd
                groups:
                  - user
  - name: projects
    provisioner:
      state_top:
        base:
          '*':
            - rundeck
            - rundeck.projects
      pillars:
        rundeck.sls:
          rundeck:
            projects:
              default:
              directory:
                resources:
                  - source: directory
                    directory: /var/rundeck/projects/${project.name}/etc/resources
              script:
                resources:
                  - source: script
                    script: /usr/bin/rd-jobs
                  - source: script
                    format: resourceyaml
                    script: /usr/bin/rd-queue
                    interpreter: /bin/sh
                    args: nodes
                    quote_interpreter_args: True
              url:
                resources:
                  - source: url
                    url: http://localhost/nodes.xml
                  - source: url
                    url: http://localhost/nodes2.xml
                    timeout: 1800
                    cache: False
              stub:
                resources:
                  - source: stub
                  - source: stub
                    prefix: fake
                    suffix: really
                    count: 2
                    tags: fake
              pillar:
                resources:
                  - source: pillar
                    nodes:
                      rundeck-server:
                        hostname: 127.0.0.1
                        username: rundeck
                      another-server:
                        hostname: 127.0.0.2
                        username: admin
                        description: Another server
                        tags: server,test
                        osFamily: unix
                        osArch: amd64
                        osName: Linux
                        osVersion: 3.16.0-0.bpo.4-amd64
                        custom: attribute
                      server-with-tags-list:
                        hostname: 127.0.0.3
                        username: user
                        tags:
                          - dev
                          - proto
  - name: jobs
    provisioner:
      state_top:
        base:
          '*':
            - rundeck
            - rundeck.projects
            - rundeck.jobs
      pillars:
        rundeck.sls:
          rundeck:
            users:
              admin:
                password: admin
                groups:
                  - user
                  - admin
            projects:
              my-project:
            jobs:
              map:
                my-project:
                  - simple-job
                  - nested/job
